name: build
on:
  push:

jobs:
  github_build:
    name: build docker
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Log in to registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build
        run: |
          set -x
          cd src
          cargo build --release --verbose

      - name: pack
        run: |
          set -x
          docker compose build web-release

      - name: push
        run: |
          TAGKEY=`docker images | grep web  | awk '{print $3}'`
          docker tag "$TAGKEY" ghcr.io/zinntikumugai/dump-web-rs
          docker push ghcr.io/zinntikumugai/dump-web-rs

